version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: nimble-chat-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: nimble_chat
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      
volumes:
  postgres-data:
